### ISSUE TITLE
[BUG] HardFault_Handle errors

### ISSUE THREAD

**Issue by soporteHW** [Sinapse-Energia/Torrot-EC-M2M#9]
When m2mMiniPCIE device is connected to a BaseBoardIoT, firmware stopped cause HardFault_Handle errors.  Memory or pointer is out of range.

It's mandatory to review all interfaces pins definitions in header file.

However, this error is not appear when m2mMiniPCIE is connected to BaseBoarEC, Why?

**Comment by ralcaide** [comment]
What is necessary to do in this issue and who??. To whom is assigned?

I think it should be created a function that publish in any MQTT topic the hard fault vector when is produced. The Atollic Pro has some functionalities to ease this process but anyway a function that publish the hard fault vector will be always useful.

Attached a guide about how to manage the HF in Atollic:

[Atollic_CortexM_crash_analysis_whitepaper.pdf](https://github.com/Sinapse-Energia/Torrot-EC-M2M/files/1061220/Atollic_CortexM_crash_analysis_whitepaper.pdf)

@francisjjp Could you make this function in order to discover the reason of the HF?, if not, @soporteHW are you able to do that?
